# Setup
name:         Cyril Wong
tagline:      Amateur coder // Good at Ctrl+V // "Write the bug, destroy the world" //
baseurl:      "https://iswxp.github.io"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
